### PR TITLE
Revert "Temporarily disable rubocop 0.92 specs in CI"

### PR DESCRIPTION
**Pull request by dvandersluis**
Reverts rubocop/rubocop-ast#198

Re-enables running rubocop 0.92's tests in CI.

### CODE REVIEW

**Comment by dvandersluis** [comment]
@marcandre I guess we need a backport for v0.92 in order to make the tests there pass?

**Comment by marcandre** [comment]
You'll have to bump 0.92 => next RuboCop version

**Comment by marcandre** [comment]
> @marcandre I guess we need a backport for v0.92 (or v0.93?) in order to make the tests there pass?

I don't think we can do much tbh. It's ok, it is unlikely we'll break compatibility in a real fashion anyways.

**Comment by pirj** [comment]
Is this still needed?

**Comment by marcandre** [comment]
Ideally yes. I'll try tweaking things in #264

**Pull request closed without merging**
