### PR TITLE
Add `multiple_elsif` to `IfNode`

### PR DESCRIPTION
**Pull request by koic**
Follow up https://github.com/rubocop/rubocop/pull/11007#discussion_r973140044.

This PR adds `multiple_elsif` to `IfNode`.

### CODE REVIEW

**Comment by marcandre** [comment]
Thanks for the PR.
This seems at first sight to be quite specific. I'm wondering if it isn't too specific to of that much used.
For example, do you foresee that will would use this method in many places of `rubocop`'s code?

**Comment by koic** [comment]
I opened this PR because I thought this feature could be made generic. But, I don't have any concrete plans to use outside of https://github.com/rubocop/rubocop/pull/11007#discussion_r973140044.

Do you think it's too early to introduce this in rubocop-ast? If so, I will close the PR because I may not have chosen the timing of the introduction well 😅

**Comment by marcandre** [comment]
Yes, let's do this, we can close this and revisit if when/if this gets used in a few places.

**Comment by koic** [comment]
I get it! Thank you for taking your time!

**Pull request closed without merging**
