### PR TITLE
Add `RuboCop::AST::RationalNode`

### PR DESCRIPTION
**Pull request by koic**
This PR resolves the fundamental issue mentioned in https://github.com/rubocop/rubocop/issues/13051. Although rational literal (e.g., `(0.2r)` is a basic literal that return `true` for `RuboCop::AST::Node#numeric_type?` and `RuboCop::AST::Node#literal?`, their behavior was not sufficiently covered as a `NumericNode`.

This PR maps rational literal to `RationalNode` to enable expected node operations for rational literals.

### CODE REVIEW

**Comment by koic** [comment]
@marcandre Can you review this?

**Comment by marcandre** [comment]
Sorry, I missed the notification, thanks for the reminder.

Looks great, thanks.

**Comment by koic** [comment]
Thank you @marcandre!

**Comment by marcandre** [comment]
Released as 1.32.0

**Pull request merged**
