### PR TITLE
Add `AST::InPatternNode` node

### PR DESCRIPTION
**Pull request by koic**
This PR adds `AST::InPatternNode` node.
It aims to make access to `in` pattern node of the pattern matching syntax convenient and readable.

For example, pattern matching syntax AST can use `in_pattern.body` and prevents the following error:

```console
NoMethodError:
  undefined method `body' for s(:in_pattern,
    s(:array_pattern,
      s(:match_var, :a)), nil,
    s(:int, 1)):RuboCop::AST::Node
```

### CODE REVIEW

**Comment by koic** [comment]
@marcandre @bbatsov I'd like to use this PR's feature in https://github.com/rubocop/rubocop/pull/9825. Can you review, merge, and release?

**Comment by bbatsov** [comment]
The change looks good to me. I'll do a release now.

**Comment by bbatsov** [comment]
Done.

**Comment by koic** [comment]
@bbatsov Thank you!

**Comment by marcandre** [comment]
Oh, this fell through the cracks, sorry 😅

Don't hesitate to ping me after 1 or 2 days

**Pull request merged**
