### PR TITLE
Add Node classes for assignment types

### PR DESCRIPTION
**Pull request by dvandersluis**
Adds nodes with a mostly unified interface for `lvasgn`, `ivasgn`, `cvasgn`, `gvasgn`, `casgn`, `op-asgn`, `and-asgn` and `or-asgn` nodes.

The idea here is that we have a lot of repeated boilerplate in some cops to handle assignment nodes that are mostly but not completely the same. This will allow all assignment nodes to respond to `name` and `expression` regardless of the node type.

I didn't create a node class for `masgn` because that works differently than everything else and I'm not exactly sure what we'd want there as of yet.

### CODE REVIEW

**Comment by dvandersluis** [comment]
Once this is available I have some cops I'd like to update to make more simple. 😄

**Comment by marcandre** [comment]
Great work 🎉

PR is great as is, but could you also update `docs/modules/ROOT/pages/node_types.adoc` please?

**Review by marcandre — APPROVED** [review]

**Comment by dvandersluis** [comment]
@marcandre absolutely! I actually had that file open to use as a reference but forgot to update the nodes 😅 Fixed now!

**Comment by marcandre** [comment]
Released 1.10.1. Thanks!

**Pull request merged**
