### PR TITLE
Enable CI on JRuby

### PR DESCRIPTION
**Pull request by marcandre**

### CODE REVIEW

**Comment by enebo** [comment]
@marcandre I noticed in GHA that JRuby is not run with --dev.  JRUBY_OPTS=--dev on my machine drops spec runs from 25s to 15s.  Hopefully takes a little sting out of adding us to CI.

**Comment by enebo** [comment]
If set as an ENV this will also speed up the bundle install as well.

**Comment by marcandre** [comment]
Cool, thanks @enebo! #175

**Comment by enebo** [comment]
@marcandre I also submitted https://github.com/ruby/setup-ruby/pull/164 which should remove 10s of installing bundler on jruby-head (I noticed truffle ruby already does this and MRI 2.7+).

**Comment by headius** [comment]
ruby/setup-ruby#164 has merged, perhaps we will see it in effect soon on rubocop-ast builds? 😀

**Comment by marcandre** [comment]
Not yet, it is installing 9.2.16 right now.

**Comment by bbatsov** [comment]
@marcandre I guess we should check if it's working now. 😅

**Comment by headius** [comment]
FWIW, current JRuby runs both `spec` and `prism_spec` green.

**Comment by marcandre** [comment]
Thanks

**Pull request merged**
